version: 2.1

jobs:
    runner:
         machine: true
         resource_class: failwhales/test
         steps:
            - run: echo "foo bar"
            - run: touch /tmp/foo
            - run: whoami
            - run: ps aux
            - run: ls -lah /proc/
            - run: ls -lah /proc/1
            - run: sudo cat /proc/1/environ

workflows:
  build_and_test:
    jobs:
      - runner
