version: 2.1

jobs:
    runner:
        machine: true
        resource_class: failwhales/test
        steps:
            - run: echo "foo bar"
            - run: touch /tmp/foo

workflows:
  build_and_test:
    jobs:
      - runner
